name: Rock Paper Scissors Game

on:
  push:
    branches: [main]

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run the game
      run: node scripts/rps.js
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Commit and push updated scores
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "update RPS leaderboard" || echo "No changes to commit"
        git push
